def expand_urls(stub, rng):
    """
    Generate list of urls over range index given a service stub.

    :param stub: Url base string for map service.
    :param rng: List of numbers generated by range() call.
    :return: List of urls beginning in stub and ending in rng values.
    """
    urls = []
    for i in rng:
        urls.append(stub + str(i))
    return urls


missing_sidewalks_base = "https://services2.arcgis.com/pc4beVTMEhYHqerq/arcgis/rest/services/missing_sidewalks_template_WFL1/FeatureServer/"
# read this in reverse so it matches the order of operational layers in the .get_data() method
# and the operational layers when building the template
url_range = list(range(11, -1, -1))
missing_sidewalks_urls = expand_urls(missing_sidewalks_base, url_range)
